# Generated by Django 5.2.8 on 2025-12-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_rating", models.IntegerField()),
                ("user_review", models.TextField()),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("ai_actions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
